spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: ibm
    password: ibm
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
    port: 8085
    
jwt:
  header: Authorization
  secret: my-very-secret-key
